identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

log:
  leak_sensitive_values: true

selfservice:
  allowed_return_urls:
    - http://127.0.0.1:4000/
    - http://127.0.0.1:4444/ # Allow redirects back to Hydra
  default_browser_return_url: http://127.0.0.1:4000/
  flows:
    error:
      ui_url: http://127.0.0.1:4000/users/register/error
    registration:
      ui_url: http://127.0.0.1:4000/users/register
      after:
        default_browser_return_url: http://127.0.0.1:4000/users/register/success
    login:
      ui_url: http://127.0.0.1:4000/users/login
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4000/
  methods:
    password:
      enabled: true
      config:
        # Bypass some password restrictions
        haveibeenpwned_enabled: false
        ignore_network_errors: true
        identifier_similarity_check_enabled: false

serve:
  public:
    base_url: http://127.0.0.1:4433
