log:
  leak_sensitive_values: true

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public

serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:4000/consent
  login: http://127.0.0.1:4000/login
  logout: http://127.0.0.1:4000/logout
  device:
    verification: http://127.0.0.1:4000/device/verify
    success: http://127.0.0.1:4000/device/success
